### ISSUE TITLE
code realease

### ISSUE THREAD

**Issue by lerndeep** [FelixHertlein/inv3d#1]
are you going to release your training and testing code? 
waiting

**Comment by FelixHertlein** [comment]
Sorry for the long wait until the release.
I do plan to release the training and testing code eventually, but right now I don't have the time for it.

If you or anyone is interested in the code without refactoring (potentially not working out of the box, no documentation), please write me an email and I can send it to you.

Regards,
Felix

**Comment by FelixHertlein** [comment]
Sorry for the long wait.

Training and evaluation code is now available!
